# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options

include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Keep these sorted

    always_put_control_body_on_new_line: false
    avoid_redundant_argument_values: false
    cascade_invocations: false
    directives_ordering: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    parameter_assignments: false
    prefer_asserts_with_message: false
    prefer_expression_function_bodies: false
    prefer_int_literals: false
    public_member_api_docs: false # TODO: enable this before publishing
    require_trailing_commas: false
    sort_constructors_first: false
