name: ensemble_llama
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  console: ^4.1.0
  ffi: ^2.1.0
  path: ^1.8.0

dev_dependencies:
  ffigen: ^9.0.1
  lints: ^2.0.0
  test: ^1.21.0

ffigen:
  name: LlamaCpp 
  description: 'FFI bindings for llama.cpp'
  output: lib/src/libllama.ffigen.dart
  headers:
    entry-points:
      - 'llama/llama.h'
  exclude-all-by-default: true
  functions:
    include:
      - 'llama_.*'