name: llamacpp
description: High and low-level dart bindings for llama.cpp
version: 1.0.0-dev
repository: https://github.com/crasm/llamacpp-dart

publish_to: none #TODO: remove to publish

environment:
  sdk: '>=3.3.0-135.0.dev <4.0.0'

dependencies:

  async: ^2.11.0
  ffi: ^2.1.0
  logging: ^1.2.0
  meta: ^1.11.0
  native_assets_cli: ^0.3.0
  native_toolchain_c: ^0.3.0
  path: ^1.8.0

dev_dependencies:

  ffigen: ^10.0.0
  test: ^1.21.0
  very_good_analysis: ^5.1.0

ffigen:
  name: 'LlamaCpp'
  description: 'FFI bindings for llama.cpp'
  output: 'lib/src/libllama.dart'
  preamble: |
    // ignore_for_file: unused_field
  headers:
    entry-points:
      - 'llama.cpp/llama.h'
    include-directives:
      - 'llama.cpp/llama.h'
      - 'llama.cpp/ggml.h'
  comments:
    style: any
    length: full
  exclude-all-by-default: true
  ffi-native:
  functions:
    include:
      - 'llama_.*'
  enums:
    include:
      - 'llama_.*'
  macros:
    include:
      - 'GGML_DEFAULT_N_THREADS'
