name: ensemble_llamacpp_server
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.3.0-135.0.dev

# Add regular dependencies here.
dependencies:
  ensemble_protos: any
  ensemble_llamacpp: any

  args: ^2.4.2
  protobuf: ^3.1.0
  grpc: ^3.2.4
  logging: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  # test: ^1.24.0
