name: ensemble_llama
description: Ensemble's high and low-level dart bindings for llama.cpp
version: 0.0.1
repository: https://github.com/crasm/ensemble/llama

publish_to: none #TODO: remove to publish

environment:
  sdk: '>=3.3.0-135.0.dev <4.0.0'

dependencies:
  ffi: ^2.1.0
  logging: ^1.2.0
  meta: ^1.11.0
  native_assets_cli: ^0.3.0
  native_toolchain_c: ^0.3.0
  path: ^1.8.0

dev_dependencies:
  ffigen: ^10.0.0
  lints: ^3.0.0
  test: ^1.21.0
  very_good_analysis: ^5.1.0
  # words: ^0.4.4

ffigen:
  name: 'LlamaCpp'
  description: 'FFI bindings for llama.cpp'
  output: lib/src/libllama.ffigen.dart
  preamble: |
    // ignore_for_file: unused_field
  headers:
    entry-points:
      - 'src/llama.h'
    include-directives:
      - 'src/llama.h'
      - 'src/ggml.h'
  comments:
    style: any
    length: full
  exclude-all-by-default: true
  ffi-native:
  functions:
    include:
      - 'llama_.*'
  enums:
    include:
      - 'llama_.*'
  macros:
    include:
      - 'GGML_DEFAULT_N_THREADS'
