name: ensemble_llama
description: Ensemble's high and low-level dart bindings for llama.cpp
version: 0.0.1
repository: https://github.com/crasm/ensemble/llama

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  logging: ^1.2.0
  native_assets_cli: ^0.3.0
  native_toolchain_c: ^0.3.0
  path: ^1.8.0

dev_dependencies:
  ffigen: ^9.0.1
  lints: ^3.0.0
  test: ^1.21.0

ffigen:
  description: 'FFI bindings for llama.cpp'
  output: lib/src/libllama.ffigen.dart
  headers:
    entry-points:
      - 'src/llama.h'
    include-directives:
      - 'src/llama.h'
  comments:
    style: any
    length: full
  exclude-all-by-default: true
  functions:
    include:
      - 'llama_.*'
  ffi-native:
